#!/bin/bash

#####################################################################
#                                                                   #
#               Build FaustWorks for MacOSX                  		#
#               with an embedded version of Faust                   #
#               (c) Grame, 2010,2011,2012,2013                      #
#                                                                   #
#####################################################################
VERSION="0.4"

DISTRIB="FaustWorks-$VERSION"

DST="FaustWorks.app/Contents/"


# then create the dmg package with the QT libraries
macdeployqt FaustWorks.app/


# creates the dmg with FaustWorks, documentation and examples

rm -rf $DISTRIB
rm -rf $DISTRIB.dmg

mkdir $DISTRIB
cp -r FaustWorks.app $DISTRIB

hdiutil create $DISTRIB.dmg -srcfolder $DISTRIB

